# Generated by Django 3.2.3 on 2021-06-10 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_Catalogo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del catalogo')),
                ('nombreCatalogo', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+-[0-9kK]{1}$')], verbose_name='Rut del Comprador')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('(\\+56|0056|56)?[ -]*(0|9)[ -]*([0-9][ -]*){8}')], verbose_name='Teléfono')),
                ('email', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[^@]+@[^@]+\\.[a-zA-Z]{2,}$')], verbose_name='Correo Electrónico')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Stock')),
                ('talla', models.CharField(max_length=4, null=True, verbose_name='Talla')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.catalogo', verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_Pedido', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del pedido')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id_detallePedido', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del detallePedido')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Cantidad del producto')),
                ('codPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido', verbose_name='Codigo de Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Codigo de Producto')),
            ],
        ),
    ]
